version: '3.8'

services:
  ai-backend:
    build:
      context: ./ai-backend
    ports:
      - "8000:8000"
    volumes:
      - ./ai-backend:/app
      - ./web/Model:/app/Model
    environment:
      - WEIGHT_DIR=predict_weight_v2
      - WEIGHT_ENSEMBLE=ensemble_cowbuff
